- hosts: square
  remote_user: pi
  gather_facts: no
  roles:
    - { role: python, become: true, ask_pass: true }
    - { role: app }
  vars:
    hostname: 10.0.1.201
    port: 8080
    group_count: 3
    LC_ALL: C
