- name: gitクローン
  git:
    repo: https://github.com/key/tbl-milan2016.git
    dest: /home/pi/app
    version: master
    accept_hostkey: yes
  become: false

- name: requirementsをインストール
  pip:
    requirements: /home/pi/app/app/requirements.txt
  become: true
  become_method: sudo
