- name: gitクローン
  git:
    repo: https://github.com/key/tbl-milan2016.git
    dest: /home/pi/app
    version: master
    accept_hostkey: yes
  become: false

- name: requirementsをインストール
  pip:
    requirements: /home/pi/app/app/requirements.txt
  become: true
  become_method: sudo

- name: htmlを生成
  template:
    src: templates/index.html
    dest: /home/pi/app/frontend/html/index.html

- name: systemdサービスの登録
  copy:
    src: files/crossbar.service
    dest: /etc/systemd/system/crossbar.service
  become: true
  become_method: sudo
